# Generated by Django 4.2.7 on 2025-12-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('content', models.TextField(help_text='About section content (HTML allowed)')),
                ('image', models.ImageField(blank=True, help_text='About section image', null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active about section will be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Company Name', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Company address')),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Website URL')),
                ('copyright_text', models.CharField(default='© 2024 Company Name. All rights reserved.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active footer will be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='header/')),
                ('logo_text', models.CharField(default='Company Name', help_text='Text to display if no logo image', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active header will be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main hero title', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle or description text')),
                ('background_image', models.ImageField(blank=True, help_text='Hero background image', null=True, upload_to='hero/')),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=50)),
                ('cta_url', models.CharField(default='#contact', help_text='CTA button URL', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active hero will be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('description', models.TextField(help_text='Service description')),
                ('image', models.ImageField(blank=True, help_text='Service image (optional)', null=True, upload_to='services/')),
                ('icon_class', models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-gear')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Menu item label', max_length=50)),
                ('url', models.CharField(default='#', help_text='URL or anchor (e.g., #about, /page/)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='website.header')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'label'],
            },
        ),
    ]
