# Generated by Django 4.2.7 on 2025-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="The number or statistic (e.g., '100+', '500', '50K')", max_length=50)),
                ('label', models.CharField(help_text="Label or description for the fact (e.g., 'Projects Completed', 'Happy Clients')", max_length=200)),
                ('icon_class', models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-people', 'bi-award')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(help_text='Product description')),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price (optional)', max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, default='USD', help_text='Price unit (e.g., USD, BDT)', max_length=20)),
                ('link', models.URLField(blank=True, help_text='Link to product page or details (optional)')),
                ('icon_class', models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-box')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
    ]
