# Generated by Django 4.2.7 on 2025-12-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_fact_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
    ]
