# Generated by Django 4.2.7 on 2025-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_product_options_remove_product_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'Facts Section', 'verbose_name_plural': 'Facts Sections'},
        ),
        migrations.RemoveField(
            model_name='fact',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='label',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='number',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='order',
        ),
        migrations.AddField(
            model_name='fact',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Facts section content (HTML allowed)'),
        ),
        migrations.AddField(
            model_name='fact',
            name='image',
            field=models.ImageField(blank=True, help_text='Facts section image', null=True, upload_to='facts/'),
        ),
        migrations.AddField(
            model_name='fact',
            name='title',
            field=models.CharField(default='Our Achievements', help_text='Facts section title', max_length=200),
        ),
        migrations.AlterField(
            model_name='fact',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active facts section will be displayed'),
        ),
    ]
